Vagrant.configure("2") do |config|
  config.vm.box = "eugenmayer/opnsense"

  config.ssh.sudo_command = "%c"
  config.ssh.shell = "/bin/sh"
  config.ssh.password = "opnsense"
  config.ssh.username = "root"
  # we need to use rsync, no vbox drivers for bsd
  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.define 'opnsense', autostart: false do |test|

    test.vm.synced_folder "./core", "/root/core", type: "rsync",
      rsync__chown: false,
      rsync__exclude: "./core/.git/"

    test.vm.provider 'virtualbox' do |vb|
      vb.customize ['modifyvm',:id, '--nic1', 'intnet', '--nic2', 'nat'] # swap the networks around
      vb.customize ['modifyvm', :id, '--natpf2', "ssh,tcp,127.0.0.1,2222,,22" ] #port forward
      vb.customize ['modifyvm', :id, '--natpf2', "https,tcp,127.0.0.1,10443,,443" ] #port forward
      vb.customize ['modifyvm', :id, '--natpf1', "https,tcp,127.0.0.1,1443,,443" ] #port forward
    end
    
    test.vm.provision "shell",
     inline: "pkg install -y vim-lite joe nano gnu-watch git tmux screen"

    test.vm.provision "shell",
     inline: "cd /root/core && make mount"
  end
end
